services:
  httpbackend:
    build: 
      context: ./
      dockerfile: docker/Dockerfile.be
    environment:
      - DATABASE_URL=postgresql://postgres:mypassword@postgres:5432
    ports:
      - "3002:3002"
    depends_on:
      - postgres
  
  fe:
    build: 
      context: ./
      dockerfile: docker/Dockerfile.fe
    environment:
      - DATABASE_URL=postgresql://postgres:mypassword@postgres:5432
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    
  ws:
    build: 
      context: ./
      dockerfile: docker/Dockerfile.ws
    environment:
      - DATABASE_URL=postgresql://postgres:mypassword@postgres:5432
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgDb:/var/lib/postgresql/data

volumes:
  pgDb: