name: "Deploy the http-backend via ci/cd"
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ## checks out the code
      - name: Checkout
        uses: actions/checkout@v4
      ## login to docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      ## build the image and push it to docker hub

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.be
          push: true
          tags: lomashchoudhary/week-27-2-be:${{github.sha}}

      ##deploy it to a VM from the docker hub
      - name: Deploy it to a VM and run using docker
        run : |
          echo "${{ secrets.PRIVATE_KEY }}" &> ~/ssh_key
          mkdir -p ~/.ssh
          touch ~/.ssh/know_hosts
          echo "${{ secrets.KNOW_HOSTS }}" &> ~/.ssh/know_hosts
          chmod 700 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@64.227.184.69 << EOF
            docker pull lomashchoudhary/week-27-2-be:${{ github.sha }}
            docker stop http-backend || true
            docker rm http-backend || true 
            docker run --restart unless-stopped -e DATABASE_URL="${{ secrets.NEON_DB }}" -d -p 3002:3002 --name http-backend lomashchoudhary/week-27-2-be:${{ github.sha }}
          EOF
          