name: Deploy the backend
on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: docker login
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and push
              uses: docker/build-push-action@v4
              with: 
                context: .
                file: ./docker/Dockerfile.be
                push: true
                tags: lomashchoudhary/week-27-2-be:${{ github.sha }}