name: Deploy the next js frontend using the ci/cd pipeline
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.fe
          build-args:
            DATABASE_URL=${{ github.DATABASE_URL }}
          push: true
          tags: lomashchoudhary/week-27-2-fe:$${{github.sha}}
