name: Deploy the ws server via ci/cd pipeline
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ##checkout the code
      - name: Checkout
        uses: actions/checkout@v4
      
      ## login to docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      ## build and push to docker hub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.ws
          push: true
          tags: lomashchoudhary/week-27-2-ws:$${{github.sha}}